# Generated by Django 5.1.6 on 2025-02-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at']},
        ),
    ]
